# Site settings
title: HERO
email: accounts@hero-app.com
description: > # this means to ignore newlines until "baseurl:"
  It’s time that someone offered a solution to reducing drunk driving. Instead
  of focusing on the negatives, we focus on making people’s lives easier and
  more rewarding. In the end, users are safer and there are less DUI’s and
  related fatalities. We optimize access to all available transportation options
  and reward designated drivers. We prove the social good in people. If it gets
  people home without driving, it can be found on the HEROapp. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"
